#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace it9
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Notes")]
	public partial class NotesDatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertPatients(Patients instance);
    partial void UpdatePatients(Patients instance);
    partial void DeletePatients(Patients instance);
    #endregion
		
		public NotesDatabaseDataContext() : 
				base(global::it9.Properties.Settings.Default.NotesConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public NotesDatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NotesDatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NotesDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NotesDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Patients> Patients
		{
			get
			{
				return this.GetTable<Patients>();
			}
		}
		
		public System.Data.Linq.Table<Doctors> Doctors
		{
			get
			{
				return this.GetTable<Doctors>();
			}
		}
		
		public System.Data.Linq.Table<Diagnosis> Diagnosis
		{
			get
			{
				return this.GetTable<Diagnosis>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Patients")]
	public partial class Patients : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Фамилия;
		
		private string _Имя;
		
		private string _Отчество;
		
		private System.Nullable<System.DateTime> _Дата_рождения;
		
		private string _СоцСтатус;
		
		private string _Состояние;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnФамилияChanging(string value);
    partial void OnФамилияChanged();
    partial void OnИмяChanging(string value);
    partial void OnИмяChanged();
    partial void OnОтчествоChanging(string value);
    partial void OnОтчествоChanged();
    partial void OnДата_рожденияChanging(System.Nullable<System.DateTime> value);
    partial void OnДата_рожденияChanged();
    partial void OnСоцСтатусChanging(string value);
    partial void OnСоцСтатусChanged();
    partial void OnСостояниеChanging(string value);
    partial void OnСостояниеChanged();
    #endregion
		
		public Patients()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Фамилия", DbType="VarChar(50)")]
		public string Фамилия
		{
			get
			{
				return this._Фамилия;
			}
			set
			{
				if ((this._Фамилия != value))
				{
					this.OnФамилияChanging(value);
					this.SendPropertyChanging();
					this._Фамилия = value;
					this.SendPropertyChanged("Фамилия");
					this.OnФамилияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Имя", DbType="VarChar(50)")]
		public string Имя
		{
			get
			{
				return this._Имя;
			}
			set
			{
				if ((this._Имя != value))
				{
					this.OnИмяChanging(value);
					this.SendPropertyChanging();
					this._Имя = value;
					this.SendPropertyChanged("Имя");
					this.OnИмяChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Отчество", DbType="VarChar(50)")]
		public string Отчество
		{
			get
			{
				return this._Отчество;
			}
			set
			{
				if ((this._Отчество != value))
				{
					this.OnОтчествоChanging(value);
					this.SendPropertyChanging();
					this._Отчество = value;
					this.SendPropertyChanged("Отчество");
					this.OnОтчествоChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата рождения]", Storage="_Дата_рождения", DbType="Date")]
		public System.Nullable<System.DateTime> Дата_рождения
		{
			get
			{
				return this._Дата_рождения;
			}
			set
			{
				if ((this._Дата_рождения != value))
				{
					this.OnДата_рожденияChanging(value);
					this.SendPropertyChanging();
					this._Дата_рождения = value;
					this.SendPropertyChanged("Дата_рождения");
					this.OnДата_рожденияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СоцСтатус", DbType="VarChar(50)")]
		public string СоцСтатус
		{
			get
			{
				return this._СоцСтатус;
			}
			set
			{
				if ((this._СоцСтатус != value))
				{
					this.OnСоцСтатусChanging(value);
					this.SendPropertyChanging();
					this._СоцСтатус = value;
					this.SendPropertyChanged("СоцСтатус");
					this.OnСоцСтатусChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Состояние", DbType="VarChar(50)")]
		public string Состояние
		{
			get
			{
				return this._Состояние;
			}
			set
			{
				if ((this._Состояние != value))
				{
					this.OnСостояниеChanging(value);
					this.SendPropertyChanging();
					this._Состояние = value;
					this.SendPropertyChanged("Состояние");
					this.OnСостояниеChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Doctors")]
	public partial class Doctors
	{
		
		private string _Фамилия;
		
		private string _Имя;
		
		private string _Отчество;
		
		private string _Должность;
		
		private string _Квалификация;
		
		private string _Специализация;
		
		public Doctors()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Фамилия", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Фамилия
		{
			get
			{
				return this._Фамилия;
			}
			set
			{
				if ((this._Фамилия != value))
				{
					this._Фамилия = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Имя", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Имя
		{
			get
			{
				return this._Имя;
			}
			set
			{
				if ((this._Имя != value))
				{
					this._Имя = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Отчество", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Отчество
		{
			get
			{
				return this._Отчество;
			}
			set
			{
				if ((this._Отчество != value))
				{
					this._Отчество = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Должность", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Должность
		{
			get
			{
				return this._Должность;
			}
			set
			{
				if ((this._Должность != value))
				{
					this._Должность = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Квалификация", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Квалификация
		{
			get
			{
				return this._Квалификация;
			}
			set
			{
				if ((this._Квалификация != value))
				{
					this._Квалификация = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Специализация", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Специализация
		{
			get
			{
				return this._Специализация;
			}
			set
			{
				if ((this._Специализация != value))
				{
					this._Специализация = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Diagnosis")]
	public partial class Diagnosis
	{
		
		private string _Диагноз;
		
		private string _Лечение;
		
		private System.DateTime _Срок_лечения;
		
		private bool _Учёт;
		
		private bool _Дата_начала_лечения;
		
		public Diagnosis()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Диагноз", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Диагноз
		{
			get
			{
				return this._Диагноз;
			}
			set
			{
				if ((this._Диагноз != value))
				{
					this._Диагноз = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Лечение", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Лечение
		{
			get
			{
				return this._Лечение;
			}
			set
			{
				if ((this._Лечение != value))
				{
					this._Лечение = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Срок лечения]", Storage="_Срок_лечения", DbType="Date NOT NULL")]
		public System.DateTime Срок_лечения
		{
			get
			{
				return this._Срок_лечения;
			}
			set
			{
				if ((this._Срок_лечения != value))
				{
					this._Срок_лечения = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Учёт", DbType="Bit NOT NULL")]
		public bool Учёт
		{
			get
			{
				return this._Учёт;
			}
			set
			{
				if ((this._Учёт != value))
				{
					this._Учёт = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата начала лечения]", Storage="_Дата_начала_лечения", DbType="Bit NOT NULL")]
		public bool Дата_начала_лечения
		{
			get
			{
				return this._Дата_начала_лечения;
			}
			set
			{
				if ((this._Дата_начала_лечения != value))
				{
					this._Дата_начала_лечения = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
